/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/basicDetails` | `/basicDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/moreDetails` | `/moreDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/profileCreated` | `/profileCreated`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/test` | `/test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/uploadProfilePicture` | `/uploadProfilePicture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/userAgreement` | `/userAgreement`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/basicDetails` | `/basicDetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/moreDetails` | `/moreDetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/profileCreated` | `/profileCreated`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/test` | `/test`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/uploadProfilePicture` | `/uploadProfilePicture`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/userAgreement` | `/userAgreement`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/basicDetails${`?${string}` | `#${string}` | ''}` | `/basicDetails${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/moreDetails${`?${string}` | `#${string}` | ''}` | `/moreDetails${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/profileCreated${`?${string}` | `#${string}` | ''}` | `/profileCreated${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/test${`?${string}` | `#${string}` | ''}` | `/test${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/uploadProfilePicture${`?${string}` | `#${string}` | ''}` | `/uploadProfilePicture${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/userAgreement${`?${string}` | `#${string}` | ''}` | `/userAgreement${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/basicDetails` | `/basicDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/moreDetails` | `/moreDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/profileCreated` | `/profileCreated`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/test` | `/test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/uploadProfilePicture` | `/uploadProfilePicture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/userAgreement` | `/userAgreement`; params?: Router.UnknownInputParams; };
    }
  }
}
